steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'frontend/Dockerfile'
      - '-t'
      - 'europe-west1-docker.pkg.dev/useful-music-440418-t0/cloud-run-source-deploy/frontend:latest'
      - '.'
images:
  - 'europe-west1-docker.pkg.dev/useful-music-440418-t0/cloud-run-source-deploy/frontend:latest'
